Error: 2021/02/04 00:21:02 log_test.go:30: The instance was down
[Error] 2021/02/04 00:21:35 log_test.go:30: The instance was down
